export enum PermissionEnum {
  PERMISSION_MANAGEMENT = 1,
  USER_MANAGEMENT = 2,
  CAMP_MANAGEMENT = 3,
  BENEF_MANAGEMENT = 4,
  DONATION_MANAGEMENT = 5,
  DONATION_APPROVE = 6,
  DONATION_REPORTING = 7,
  CAMP_REPORTING = 8,
  CAMP_IMPORT = 9,
  CAMP_REPORT_RESTRICTED = 10
}




